## Numpy

In [1]:
import numpy as np

### Problem 3

In [2]:
n = np.random.randint(1, 10, (3, 5))
n

array([[7, 9, 6, 6, 9],
       [9, 6, 5, 5, 9],
       [1, 8, 2, 9, 7]])

### Problem 4

In [3]:
x = np.zeros(10, dtype=np.int)
x[4] = 3
x
print(x)

[0 0 0 0 3 0 0 0 0 0]


### Problem 5

In [4]:
x = np.arange(3, 15)
x

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Problem 6

In [5]:
x = np.array([1, 3, 5, 2, 4, 5])

In [6]:
x.reshape(3,2)

array([[1, 3],
       [5, 2],
       [4, 5]])

In [7]:
x.reshape(2,3)

array([[1, 3, 5],
       [2, 4, 5]])

In [8]:
x

array([1, 3, 5, 2, 4, 5])

### Problem 7

In [10]:
def mean_np(n):
    while n.mean()>5:
        n = n / 2
    if n.mean()<=5:
        return n
    
x = np.arange(7, 25)
x.mean()

15.5

In [11]:
mean_np(x)

array([1.75, 2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25,
       4.5 , 4.75, 5.  , 5.25, 5.5 , 5.75, 6.  ])

### Problem 8

In [14]:
n = np.random.randint(1, 10, (5,4))
n

array([[4, 2, 5, 5],
       [7, 8, 6, 2],
       [6, 8, 3, 7],
       [5, 6, 6, 1],
       [1, 6, 6, 1]])

In [20]:
print(n[..., 0])
print(n[..., 1])

[4 7 6 5 1]
[2 8 8 6 6]


In [23]:
def columns_of_array(x):
    print(x[..., 0])
    print(x[..., 1])
    print(x[..., 2])
    print(x[..., 3])

In [24]:
columns_of_array(n)

[4 7 6 5 1]
[2 8 8 6 6]
[5 6 3 6 6]
[5 2 7 1 1]


In [27]:
print(n[0, ...])

[4 2 5 5]


In [31]:
def rows_of_array(x):
    print(x[0, ...])
    print(x[1, ...])
    print(x[2, ...])
    print(x[3, ...])
    print(x[4, ...])

In [32]:
rows_of_array(n)

[4 2 5 5]
[7 8 6 2]
[6 8 3 7]
[5 6 6 1]
[1 6 6 1]
